linters:
  enable-all: false
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unparam
    - unused
    - varcheck
    - whitespace
    # following linters produce a lot false positives, enable only when needed:
    # - gosec
    # - scopelint
    # not using structcheck since it doesn't handle embedded structs

linters-settings:
  govet:
    disable:
      - shadow # reports a lot of false-positives and conflicts with other linters
  golint:
    min-confidence: 0
  errcheck:
    check-blank: true
    check-type-assertions: false
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - commentFormatting
      - dupImport
  prealloc:
    simple: true # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: true # Report preallocation suggestions on for loops, false by default
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US

issues:
  # use default exclude rules
  exclude-use-default: true

  # additional exclude rules
  exclude-rules:
    - linters: errcheck
      text: "Error return value of" # ignores 'error return value of ... is unchecked'
    - linters: golint
      text: "Example_"

  # Set to 0 to disable limit
  max-same-issues: 0
  max-per-linter: 0

run:
  tests: true # enable linting test files

  concurrency: 4
  deadline: 5m
